name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Setup cache
        uses: Swatinem/rust-cache@v1

      - run: cargo doc --all-features --no-deps
      - run: echo "<meta http-equiv=\"refresh\" content=\"0; url=rs_cord\">" > target/doc/index.html
      - run: cp -r target/doc ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
