name: Build & Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install latest Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Setup cache
      uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build --all-features --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug
        path: target/debug/librs_cord.rlib

    - name: Run tests
      run: cargo test --all-features --verbose
  
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Setup cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release --all-features --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: target/release/librs_cord.rlib

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly with clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v1

      - name: Clippy lint
        run: cargo clippy --all-features -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo
